## Reading the Data

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv("FS 06-07-25.csv")
df

,month_accid,year_month,account_id,months_since_rd,months_bw_ftd_n_rd,months_bw_fwd_n_rd,amount_of_effectivedeposits,deposits_success_rate,w2ic,actively_playing_days,...,acq_channel_PPC,acq_channel_SEO,acq_channel_SMM,device_type_desktop,device_type_mobile,device_type_mobile_native_apk,device_type_mobile_native_apk_free,device_type_mobile_native_ipa,device_type_mobile_native_ps,future_state
0,2024-09_129,2024-09,129,167,25.0,98.0,0.00,0.0,0,1,...,0,0,0,0,1,0,0,0,0,0.0
1,2023-11_129,2023-11,129,157,25.0,98.0,0.00,0.0,0,1,...,0,0,0,0,1,0,0,0,0,0.0
2,2024-03_129,2024-03,129,161,25.0,98.0,0.00,0.0,0,1,...,0,0,0,0,1,0,0,0,0,0.0
3,2024-06_130,2024-06,130,164,29.0,86.0,0.00,0.0,0,1,...,0,0,0,1,0,0,0,0,0,0.0
4,2024-04_130,2024-04,130,162,29.0,86.0,0.00,0.0,0,1,...,0,0,0,1,0,0,0,0,0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302138,2025-06_5870598,2025-06,5870598,0,0.0,0.0,215.61,1.0,0,1,...,0,0,0,0,0,0,0,0,1,NaN
302139,2025-06_5870623,2025-06,5870623,0,0.0,0.0,39.06,1.0,0,1,...,0,0,0,0,0,0,0,1,0,NaN
302140,2025-06_5870699,2025-06,5870699,0,0.0,0.0,117.18,1.0,0,1,...,0,0,0,0,0,1,0,0,0,NaN
302141,2025-06_5870724,2025-06,5870724,0,0.0,0.0,156.25,1.0,0,1,...,0,0,0,0,0,0,0,0,1,NaN
302142,2025-06_5870740,2025-06,5870740,0,0.0,0.0,78.12,1.0,0,1,...,0,0,0,0,0,1,0,0,0,NaN

## Imputing the Nulls

In [7]:
df.isnull().sum()[df.isnull().sum() != 0].index

Index(['months_bw_ftd_n_rd', 'months_bw_fwd_n_rd', 'expired_bonus',
       'total_bonus_credited', 'cash_bonus_issued_pct',
       'pending_bonus_issued_pct', 'manual_credits_specialtourney_issued_pct',
       'future_state'],
      dtype='object')

In [9]:
df.fillna(0, inplace = True)

In [11]:
df2 = df[df['year_month'] != '2025-06']

In [13]:
X = df2.iloc[:, 3:-1]
X

,months_since_rd,months_bw_ftd_n_rd,months_bw_fwd_n_rd,amount_of_effectivedeposits,deposits_success_rate,w2ic,actively_playing_days,reactivated,withdrawal_dep_ratio,no_of_withdrawals,...,acq_channel_Others,acq_channel_PPC,acq_channel_SEO,acq_channel_SMM,device_type_desktop,device_type_mobile,device_type_mobile_native_apk,device_type_mobile_native_apk_free,device_type_mobile_native_ipa,device_type_mobile_native_ps
0,167,25.0,98.0,0.00,0.000000,0,1,1,0.0,0,...,0,0,0,0,0,1,0,0,0,0
1,157,25.0,98.0,0.00,0.000000,0,1,1,0.0,0,...,0,0,0,0,0,1,0,0,0,0
2,161,25.0,98.0,0.00,0.000000,0,1,1,0.0,0,...,0,0,0,0,0,1,0,0,0,0
3,164,29.0,86.0,0.00,0.000000,0,1,0,0.0,0,...,0,0,0,0,1,0,0,0,0,0
4,162,29.0,86.0,0.00,0.000000,0,1,0,0.0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291246,0,0.0,0.0,39.06,1.000000,0,1,0,0.0,0,...,0,0,0,0,0,0,1,0,0,0
291247,0,0.0,0.0,39.06,0.500000,0,1,0,0.0,0,...,0,0,0,0,0,0,0,0,0,1
291248,0,0.0,0.0,468.74,1.000000,0,1,0,0.0,0,...,0,0,0,0,0,0,0,0,0,1
291249,0,0.0,0.0,117.18,1.000000,0,1,0,0.0,0,...,0,0,0,0,0,0,0,0,0,1
291250,0,0.0,0.0,312.48,0.777778,0,1,0,0.0,0,...,0,0,0,0,0,0,1,0,0,0

## Eliminating Insignificant Variables using P-Value and VIF

In [15]:
y = df2['future_state']

In [23]:
X.drop(columns =['state_KL', 'Pools_2_Low_gr_pct', 'Pools_6_Low_gr_pct',
       'monday_gp_pct', 'pending_bonus_issued_pct', 'thursday_gp_pct',
       'winnings_per_game', 'Strikes_2_Low_winpct', 'tuesday_gp_pct',
       'avg_withdrawal_tat_hours', 'city_tier_Tier 2',
       'Deals_2_Low_gr_pct', 'saturday_gp_pct', 'city_tier_Tier 3',
       'Pools_6_High_gr_pct'], inplace = True)

In [29]:
X.drop(columns = ['state_TN'], inplace = True)

In [39]:
X.drop(columns =['device_type_mobile_native_ps', 'acq_channel_PPC', 'gender_Others',
        'device_brand_Budget'], inplace = True)

In [45]:
X.drop(columns =['device_type_mobile', 'acq_channel_SEO'], inplace = True)

In [ ]:
'state_KL', 'Pools_2_Low_gr_pct', 'Pools_6_Low_gr_pct',
       'monday_gp_pct', 'pending_bonus_issued_pct', 'thursday_gp_pct',
       'winnings_per_game', 'Strikes_2_Low_winpct', 'tuesday_gp_pct',
       'avg_withdrawal_tat_hours', 'city_tier_Tier 2',
       'Deals_2_Low_gr_pct', 'saturday_gp_pct', 'city_tier_Tier 3',
       'Pools_6_High_gr_pct','state_TN','device_type_mobile_native_ps', 'acq_channel_PPC', 'gender_Others',
        'device_brand_Budget','device_type_mobile', 'acq_channel_SEO'

In [17]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

In [47]:
Xc = sm.add_constant(X)

# Fit the model
model = sm.OLS(y, Xc).fit()

# Get p-values
p_values = model.pvalues
p_values = pd.DataFrame(p_values).reset_index().rename(columns = {'index':'Variable', 0:'P-Value'}).sort_values(by="P-Value", ascending=False)

In [49]:
p_values[p_values['P-Value'] > 0.2]['Variable'].values

array([], dtype=object)

In [51]:
vif_data = pd.DataFrame()
vif_data["Feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
vif = vif_data.sort_values(by="VIF", ascending=False)
vif.set_index('Feature', inplace=True)

In [53]:
vif[vif['VIF'] > 20].index

Index([], dtype='object', name='Feature')

## Defining the Test and Train

In [55]:
train = df[(df['year_month'] != '2025-05') & (df['year_month'] != '2025-06')]
test = df[df['year_month'] == '2025-05']
cur = df[df['year_month'] == '2025-06']

print(train.shape)
print(test.shape)
cur.shape

(280312, 93)
(10939, 93)

(10892, 93)

In [57]:
X_train = train.iloc[:, 3:-1]
train_tar = train.iloc[:, -1:]
X_test = test.iloc[:, 3:-1]
test_tar = test.iloc[:, -1:]
cur_test_f = cur.iloc[:, 3:-1]
cur_tar = cur.iloc[:, -1:]

In [59]:
X_train.drop(columns = ['state_KL', 'Pools_2_Low_gr_pct', 'Pools_6_Low_gr_pct',
       'monday_gp_pct', 'pending_bonus_issued_pct', 'thursday_gp_pct',
       'winnings_per_game', 'Strikes_2_Low_winpct', 'tuesday_gp_pct',
       'avg_withdrawal_tat_hours', 'city_tier_Tier 2',
       'Deals_2_Low_gr_pct', 'saturday_gp_pct', 'city_tier_Tier 3',
       'Pools_6_High_gr_pct','state_TN','device_type_mobile_native_ps', 'acq_channel_PPC', 'gender_Others',
        'device_brand_Budget','device_type_mobile', 'acq_channel_SEO'], inplace = True)

X_test.drop(columns = ['state_KL', 'Pools_2_Low_gr_pct', 'Pools_6_Low_gr_pct',
       'monday_gp_pct', 'pending_bonus_issued_pct', 'thursday_gp_pct',
       'winnings_per_game', 'Strikes_2_Low_winpct', 'tuesday_gp_pct',
       'avg_withdrawal_tat_hours', 'city_tier_Tier 2',
       'Deals_2_Low_gr_pct', 'saturday_gp_pct', 'city_tier_Tier 3',
       'Pools_6_High_gr_pct','state_TN','device_type_mobile_native_ps', 'acq_channel_PPC', 'gender_Others',
        'device_brand_Budget','device_type_mobile', 'acq_channel_SEO'], inplace = True)

cur_test_f.drop(columns = ['state_KL', 'Pools_2_Low_gr_pct', 'Pools_6_Low_gr_pct',
       'monday_gp_pct', 'pending_bonus_issued_pct', 'thursday_gp_pct',
       'winnings_per_game', 'Strikes_2_Low_winpct', 'tuesday_gp_pct',
       'avg_withdrawal_tat_hours', 'city_tier_Tier 2',
       'Deals_2_Low_gr_pct', 'saturday_gp_pct', 'city_tier_Tier 3',
       'Pools_6_High_gr_pct','state_TN','device_type_mobile_native_ps', 'acq_channel_PPC', 'gender_Others',
        'device_brand_Budget','device_type_mobile', 'acq_channel_SEO'], inplace = True)

## Standardizing the Data

In [61]:
from sklearn.preprocessing import StandardScaler

# Initialize the scaler
scaler = StandardScaler()

In [63]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
cur_test_scaled = scaler.transform(cur_test_f)

y_train = train_tar['future_state']
y_test = test_tar['future_state']
cur_test = cur_tar['future_state']

In [65]:
X_train

,months_since_rd,months_bw_ftd_n_rd,months_bw_fwd_n_rd,amount_of_effectivedeposits,deposits_success_rate,w2ic,actively_playing_days,reactivated,withdrawal_dep_ratio,no_of_withdrawals,...,device_brand_Generic,device_brand_Mid Range,device_brand_Premium,acq_channel_Affiliate,acq_channel_Others,acq_channel_SMM,device_type_desktop,device_type_mobile_native_apk,device_type_mobile_native_apk_free,device_type_mobile_native_ipa
0,167,25.0,98.0,0.00,0.0,0,1,1,0.0,0,...,1,0,0,1,0,0,0,0,0,0
1,157,25.0,98.0,0.00,0.0,0,1,1,0.0,0,...,1,0,0,1,0,0,0,0,0,0
2,161,25.0,98.0,0.00,0.0,0,1,1,0.0,0,...,1,0,0,1,0,0,0,0,0,0
3,164,29.0,86.0,0.00,0.0,0,1,0,0.0,0,...,1,0,0,1,0,0,1,0,0,0
4,162,29.0,86.0,0.00,0.0,0,1,0,0.0,0,...,1,0,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280307,0,0.0,0.0,78.12,0.5,0,1,0,0.0,0,...,0,0,1,1,0,0,0,0,0,0
280308,0,0.0,0.0,156.25,1.0,0,1,0,0.0,0,...,1,0,0,1,0,0,0,1,0,0
280309,0,1.0,0.0,0.00,0.0,0,1,0,0.0,0,...,0,1,0,1,0,0,0,0,0,0
280310,0,0.0,0.0,39.06,1.0,0,1,0,0.0,0,...,1,0,0,1,0,0,0,1,0,0
280311,0,0.0,0.0,39.06,1.0,0,1,0,0.0,0,...,0,1,0,1,0,0,0,1,0,0

In [385]:
y_train.value_counts()

Future State
3.0    6260
2.0    3005
4.0    2618
1.0    1617
0.0    1362
Name: count, dtype: int64

## Building the Logistic Regression Model

In [67]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

### Test Accuracy

In [69]:
log_reg1 = LogisticRegression(solver='lbfgs', max_iter=1000)


# Train the model
log_reg1.fit(X_train_scaled, y_train)

# Make predictions
y_pred = log_reg1.predict(X_test_scaled)


y_proba = log_reg1.predict_proba(X_test_scaled)

proba_df1lr = pd.DataFrame(y_proba, columns=[f"Class_{i}_Prob" for i in range(5)])

class_labels = [f"Class_{i}" for i in range(log_reg1.coef_.shape[0])]

coef_df = pd.DataFrame(log_reg1.coef_, columns=X_train.columns, index=class_labels)

# Add intercept to the DataFrame
intercept_df = pd.DataFrame(log_reg1.intercept_, columns=["Intercept"], index=class_labels)

# Combine coefficients and intercepts
coef_with_intercept_df1 = pd.concat([intercept_df, coef_df], axis=1)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Print evaluation metrics
print('MH Model Test')
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{class_report}")

y_test = pd.Series(y_test, name="Actual")
y_pred = pd.Series(y_pred, name="Predicted", index=y_test.index)

# Combine them into a DataFrame
avp1lr = pd.DataFrame({"Actual": y_test, "Predicted": y_pred})

MH Model Test
Accuracy: 0.7106682512112624
Confusion Matrix:
[[5878  128  266   17   12]
 [ 474  240  357   87   20]
 [ 922  112 1220   97    5]
 [  95   70  322  326   37]
 [  12   16   12  104  110]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.80      0.93      0.86      6301
         1.0       0.42      0.20      0.28      1178
         2.0       0.56      0.52      0.54      2356
         3.0       0.52      0.38      0.44       850
         4.0       0.60      0.43      0.50       254

    accuracy                           0.71     10939
   macro avg       0.58      0.49      0.52     10939
weighted avg       0.68      0.71      0.69     10939

In [71]:
avp1lr.reset_index(inplace = True, drop = True)
proba_df1lr['actuals'] = avp1lr['Actual']

### Train Accuracy

In [73]:
# Make predictions
y_pred = log_reg1.predict(X_train_scaled)


y_proba = log_reg1.predict_proba(X_train_scaled)

proba_df2lr = pd.DataFrame(y_proba, columns=[f"Class_{i}_Prob" for i in range(5)])

# Evaluate the model
accuracy = accuracy_score(y_train, y_pred)
conf_matrix = confusion_matrix(y_train, y_pred)
class_report = classification_report(y_train, y_pred)

# Print evaluation metrics
print('MH Model Train')
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{class_report}")

y_ = pd.Series(y_train, name="Actual")
y_pred = pd.Series(y_pred, name="Predicted", index=y_.index)

# Combine them into a DataFrame
avp2lr = pd.DataFrame({"Actual": y_, "Predicted": y_pred})

MH Model Train
Accuracy: 0.6341754901680984
Confusion Matrix:
[[131929   2633   6932    285    152]
 [ 29851   7192  10901   1693    380]
 [ 26917   2998  30116   2331    133]
 [  2424   2110   8351   6270    722]
 [   449    665    389   2229   2260]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.69      0.93      0.79    141931
         1.0       0.46      0.14      0.22     50017
         2.0       0.53      0.48      0.51     62495
         3.0       0.49      0.32      0.38     19877
         4.0       0.62      0.38      0.47      5992

    accuracy                           0.63    280312
   macro avg       0.56      0.45      0.47    280312
weighted avg       0.60      0.63      0.59    280312

### Predicting for the Current Month

In [75]:
y_pred = log_reg1.predict(cur_test_scaled)


y_proba = log_reg1.predict_proba(cur_test_scaled)

proba_df3lr = pd.DataFrame(y_proba, columns=[f"Class_{i}_Prob" for i in range(5)])

In [81]:
cur.reset_index(drop = True, inplace = True)

In [77]:
test.reset_index(drop = True, inplace = True)

In [79]:
proba_df1lr['account_id'] = test['account_id']
proba_df1lr

,Class_0_Prob,Class_1_Prob,Class_2_Prob,Class_3_Prob,Class_4_Prob,actuals,account_id
0,0.166401,0.449337,0.374856,0.009260,0.000146,0.0,165
1,0.000303,0.081907,0.629373,0.262663,0.025754,2.0,555
2,0.523908,0.184169,0.279254,0.011147,0.001523,0.0,557
3,0.300248,0.261303,0.357408,0.076158,0.004883,1.0,801
4,0.099305,0.226414,0.546679,0.120583,0.007019,2.0,981
...,...,...,...,...,...,...,...
10934,0.863657,0.054117,0.076679,0.004929,0.000619,0.0,5858099
10935,0.770043,0.111244,0.113440,0.005067,0.000206,0.0,5858101
10936,0.752206,0.116434,0.123273,0.007629,0.000460,0.0,5858141
10937,0.727029,0.113049,0.149658,0.009847,0.000417,0.0,5858151
10938,0.689121,0.141916,0.157115,0.011354,0.000494,2.0,5858176

In [83]:
proba_df3lr['account_id'] = cur['account_id']
proba_df3lr

,Class_0_Prob,Class_1_Prob,Class_2_Prob,Class_3_Prob,Class_4_Prob,account_id
0,0.000059,0.300031,0.514846,0.162810,0.022254,555
1,0.309559,0.304506,0.338450,0.044831,0.002653,801
2,0.115558,0.209450,0.577965,0.092124,0.004905,981
3,0.152221,0.279067,0.534102,0.032417,0.002194,1197
4,0.000001,0.194643,0.088275,0.492139,0.224942,1259
...,...,...,...,...,...,...
10887,0.737495,0.097016,0.153884,0.011113,0.000492,5870598
10888,0.876113,0.040736,0.080228,0.002665,0.000257,5870623
10889,0.828462,0.065488,0.100622,0.005250,0.000178,5870699
10890,0.744897,0.112285,0.132910,0.009489,0.000419,5870724
10891,0.856722,0.044535,0.091423,0.006427,0.000894,5870740

In [85]:
import re

In [87]:
declr = proba_df1lr
decile_analysis = pd.DataFrame()

# Process each class
for class_label in ['Class_0_Prob', 'Class_1_Prob', 'Class_2_Prob','Class_3_Prob','Class_4_Prob']:
    declr[f'{class_label}_decile'] = pd.qcut(declr[class_label], 10, labels=False, duplicates='drop') + 1

    # Create a temporary column for actual class match
    current_class = int(class_label.split('_')[1])  # Extract class number from column name
    declr['is_actual_class'] = (declr['actuals'] == current_class).astype(int)

    # Aggregate metrics for the current class
    class_decile = declr.groupby(f'{class_label}_decile').agg(
        total_count=('actuals', 'count'),
        actual_class_count=('is_actual_class', 'sum'),
        avg_predicted_prob=(class_label, 'mean')
    ).reset_index()

    # Add class label for context
    class_decile['class'] = current_class

    # Append to the main DataFrame
    decile_analysis = pd.concat([decile_analysis, class_decile], ignore_index=True)

# Sort by class and decile
decile_analysis = decile_analysis.sort_values(by=['class', f'{class_label}_decile'], ascending=[True, False])
decile_analysis

,Class_0_Prob_decile,total_count,actual_class_count,avg_predicted_prob,class,Class_1_Prob_decile,Class_2_Prob_decile,Class_3_Prob_decile,Class_4_Prob_decile
0,1.0,1094,12,0.003137,0,NaN,NaN,NaN,NaN
1,2.0,1094,80,0.039142,0,NaN,NaN,NaN,NaN
2,3.0,1094,229,0.196284,0,NaN,NaN,NaN,NaN
3,4.0,1094,472,0.397636,0,NaN,NaN,NaN,NaN
4,5.0,1094,709,0.551835,0,NaN,NaN,NaN,NaN
5,6.0,1093,862,0.657157,0,NaN,NaN,NaN,NaN
6,7.0,1094,939,0.727094,0,NaN,NaN,NaN,NaN
7,8.0,1094,955,0.783351,0,NaN,NaN,NaN,NaN
8,9.0,1094,994,0.843454,0,NaN,NaN,NaN,NaN
9,10.0,1094,1049,0.899245,0,NaN,NaN,NaN,NaN
10,NaN,1094,24,0.032396,1,1.0,NaN,NaN,NaN
11,NaN,1094,32,0.064000,1,2.0,NaN,NaN,NaN
12,NaN,1094,53,0.086969,1,3.0,NaN,NaN,NaN
13,NaN,1094,55,0.112012,1,4.0,NaN,NaN,NaN
14,NaN,1094,51,0.135191,1,5.0,NaN,NaN,NaN
15,NaN,1093,80,0.156341,1,6.0,NaN,NaN,NaN
16,NaN,1094,78,0.182394,1,7.0,NaN,NaN,NaN
17,NaN,1094,162,0.218870,1,8.0,NaN,NaN,NaN
18,NaN,1094,241,0.269244,1,9.0,NaN,NaN,NaN
19,NaN,1094,402,0.394330,1,10.0,NaN,NaN,NaN
20,NaN,1094,28,0.031457,2,NaN,1.0,NaN,NaN
21,NaN,1094,37,0.058438,2,NaN,2.0,NaN,NaN
22,NaN,1094,77,0.079167,2,NaN,3.0,NaN,NaN
23,NaN,1094,118,0.103503,2,NaN,4.0,NaN,NaN
24,NaN,1094,117,0.134097,2,NaN,5.0,NaN,NaN
25,NaN,1093,213,0.176213,2,NaN,6.0,NaN,NaN
26,NaN,1094,230,0.231212,2,NaN,7.0,NaN,NaN
27,NaN,1094,310,0.311831,2,NaN,8.0,NaN,NaN
28,NaN,1094,477,0.442422,2,NaN,9.0,NaN,NaN
29,NaN,1094,749,0.627294,2,NaN,10.0,NaN,NaN
30,NaN,1094,1,0.000638,3,NaN,NaN,1.0,NaN
31,NaN,1094,5,0.001585,3,NaN,NaN,2.0,NaN
32,NaN,1094,4,0.003880,3,NaN,NaN,3.0,NaN
33,NaN,1094,8,0.006864,3,NaN,NaN,4.0,NaN
34,NaN,1094,11,0.011274,3,NaN,NaN,5.0,NaN
35,NaN,1093,12,0.020679,3,NaN,NaN,6.0,NaN
36,NaN,1094,43,0.039889,3,NaN,NaN,7.0,NaN
37,NaN,1094,92,0.084166,3,NaN,NaN,8.0,NaN
38,NaN,1094,197,0.187287,3,NaN,NaN,9.0,NaN
39,NaN,1094,477,0.438178,3,NaN,NaN,10.0,NaN
49,NaN,1094,234,0.223900,4,NaN,NaN,NaN,10.0
48,NaN,1094,13,0.021035,4,NaN,NaN,NaN,9.0
47,NaN,1094,3,0.007548,4,NaN,NaN,NaN,8.0
46,NaN,1094,0,0.003494,4,NaN,NaN,NaN,7.0
45,NaN,1093,3,0.001830,4,NaN,NaN,NaN,6.0
44,NaN,1094,0,0.001049,4,NaN,NaN,NaN,5.0
43,NaN,1094,0,0.000606,4,NaN,NaN,NaN,4.0
42,NaN,1094,0,0.000300,4,NaN,NaN,NaN,3.0
41,NaN,1094,1,0.000075,4,NaN,NaN,NaN,2.0
40,NaN,1094,0,0.000019,4,NaN,NaN,NaN,1.0

In [89]:
with pd.ExcelWriter('FS Model Results 06-07-25.xlsx', engine='xlsxwriter') as writer:
    proba_df3lr.to_excel(writer, sheet_name='Jul Probs', index = False)
    decile_analysis.to_excel(writer, sheet_name='Decile Analysis', index = False)

In [ ]:
# Random Forest

In [101]:
from sklearn.ensemble import RandomForestClassifier

In [97]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
sep_test_scaled = scaler.transform(sep_test_f)

y_train = train_tar['Future State']
y_test = test_tar['Future State']
sep_test = sep_tar['Future State']

In [103]:
# Initialize the Random Forest classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = rf_model.predict(X_test_scaled)

y_proba = rf_model.predict_proba(X_test_scaled)
proba_df1rf = pd.DataFrame(y_proba, columns=[f"Class_{i}_Prob" for i in range(5)])
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred))

y_test = pd.Series(y_test, name="Actual")
y_pred = pd.Series(y_pred, name="Predicted", index=y_test.index)

# Combine them into a DataFrame
avp1rf = pd.DataFrame({"Actual": y_test, "Predicted": y_pred})

Confusion Matrix:
[[ 246   17   51  129   27]
 [  38   35   48  264   65]
 [  41   16  190  676   35]
 [  45   37  181 1542  233]
 [  15   11   10  296  537]]

Classification Report:
              precision    recall  f1-score   support

           0       0.64      0.52      0.58       470
           1       0.30      0.08      0.12       450
           2       0.40      0.20      0.26       958
           3       0.53      0.76      0.62      2038
           4       0.60      0.62      0.61       869

    accuracy                           0.53      4785
   macro avg       0.49      0.43      0.44      4785
weighted avg       0.51      0.53      0.50      4785


Accuracy Score:
0.5329153605015674

In [170]:
avp1rf.reset_index(drop=True, inplace= True)

In [172]:
proba_df1rf['actuals'] = avp1rf['Actual']

In [174]:
proba_df1rf

,Class_0_Prob,Class_1_Prob,Class_2_Prob,Class_3_Prob,Class_4_Prob,Class_0_Prob_decile,actuals
0,0.00,0.02,0.31,0.63,0.04,1,2
1,0.07,0.16,0.24,0.42,0.11,6,4
2,0.07,0.12,0.19,0.46,0.16,6,4
3,0.07,0.02,0.40,0.51,0.00,6,3
4,0.07,0.01,0.43,0.49,0.00,6,2
...,...,...,...,...,...,...,...
4780,0.09,0.12,0.09,0.26,0.44,7,4
4781,0.21,0.17,0.14,0.33,0.15,9,2
4782,0.16,0.22,0.12,0.27,0.23,9,1
4783,0.06,0.09,0.25,0.41,0.19,6,4
4784,0.03,0.10,0.32,0.51,0.04,3,3

## Decile Analysis

In [176]:
declr = proba_df1rf
decile_analysis = pd.DataFrame()

# Process each class
for class_label in ['Class_0_Prob', 'Class_1_Prob', 'Class_2_Prob','Class_3_Prob','Class_4_Prob']:
    declr[f'{class_label}_decile'] = pd.qcut(declr[class_label], 10, labels=False, duplicates='drop') + 1

    # Create a temporary column for actual class match
    current_class = int(class_label.split('_')[1])  # Extract class number from column name
    declr['is_actual_class'] = (declr['actuals'] == current_class).astype(int)

    # Aggregate metrics for the current class
    class_decile = declr.groupby(f'{class_label}_decile').agg(
        total_count=('actuals', 'count'),
        actual_class_count=('is_actual_class', 'sum'),
        avg_predicted_prob=(class_label, 'mean')
    ).reset_index()

    # Add class label for context
    class_decile['class'] = current_class

    # Append to the main DataFrame
    decile_analysis = pd.concat([decile_analysis, class_decile], ignore_index=True)

# Sort by class and decile
decile_analysis = decile_analysis.sort_values(by=['class', f'{class_label}_decile'], ascending=[True, False])
decile_analysis.to_csv('da_rf_3,4.csv')
decile_analysis

,Class_0_Prob_decile,total_count,actual_class_count,avg_predicted_prob,class,Class_1_Prob_decile,Class_2_Prob_decile,Class_3_Prob_decile,Class_4_Prob_decile
0,1.0,813,5,0.006224,0,NaN,NaN,NaN,NaN
1,2.0,511,8,0.020000,0,NaN,NaN,NaN,NaN
2,3.0,478,13,0.030000,0,NaN,NaN,NaN,NaN
3,4.0,383,8,0.040000,0,NaN,NaN,NaN,NaN
4,5.0,366,17,0.050000,0,NaN,NaN,NaN,NaN
5,6.0,562,16,0.064680,0,NaN,NaN,NaN,NaN
6,7.0,343,19,0.084052,0,NaN,NaN,NaN,NaN
7,8.0,443,49,0.113589,0,NaN,NaN,NaN,NaN
8,9.0,430,68,0.176000,0,NaN,NaN,NaN,NaN
9,10.0,456,267,0.482039,0,NaN,NaN,NaN,NaN
10,NaN,494,8,0.021478,1,1.0,NaN,NaN,NaN
11,NaN,541,15,0.045250,1,2.0,NaN,NaN,NaN
12,NaN,566,32,0.065212,1,3.0,NaN,NaN,NaN
13,NaN,552,42,0.084982,1,4.0,NaN,NaN,NaN
14,NaN,278,19,0.100000,1,5.0,NaN,NaN,NaN
15,NaN,506,50,0.114822,1,6.0,NaN,NaN,NaN
16,NaN,448,46,0.134420,1,7.0,NaN,NaN,NaN
17,NaN,515,63,0.158932,1,8.0,NaN,NaN,NaN
18,NaN,436,57,0.194014,1,9.0,NaN,NaN,NaN
19,NaN,449,118,0.270022,1,10.0,NaN,NaN,NaN
20,NaN,556,13,0.031043,2,NaN,1.0,NaN,NaN
21,NaN,522,35,0.074866,2,NaN,2.0,NaN,NaN
22,NaN,376,35,0.109894,2,NaN,3.0,NaN,NaN
23,NaN,492,64,0.145081,2,NaN,4.0,NaN,NaN
24,NaN,503,87,0.186501,2,NaN,5.0,NaN,NaN
25,NaN,463,103,0.224903,2,NaN,6.0,NaN,NaN
26,NaN,439,93,0.266014,2,NaN,7.0,NaN,NaN
27,NaN,522,144,0.309847,2,NaN,8.0,NaN,NaN
28,NaN,444,161,0.363739,2,NaN,9.0,NaN,NaN
29,NaN,468,223,0.450342,2,NaN,10.0,NaN,NaN
30,NaN,519,56,0.119730,3,NaN,NaN,1.0,NaN
31,NaN,477,110,0.222830,3,NaN,NaN,2.0,NaN
32,NaN,479,155,0.280251,3,NaN,NaN,3.0,NaN
33,NaN,512,188,0.329453,3,NaN,NaN,4.0,NaN
34,NaN,431,173,0.374362,3,NaN,NaN,5.0,NaN
35,NaN,478,219,0.419791,3,NaN,NaN,6.0,NaN
36,NaN,498,267,0.468896,3,NaN,NaN,7.0,NaN
37,NaN,436,232,0.519794,3,NaN,NaN,8.0,NaN
38,NaN,516,323,0.582771,3,NaN,NaN,9.0,NaN
39,NaN,439,315,0.684260,3,NaN,NaN,10.0,NaN
49,NaN,466,335,0.628734,4,NaN,NaN,NaN,10.0
48,NaN,462,219,0.407619,4,NaN,NaN,NaN,9.0
47,NaN,484,129,0.272128,4,NaN,NaN,NaN,8.0
46,NaN,432,71,0.176597,4,NaN,NaN,NaN,7.0
45,NaN,416,43,0.123389,4,NaN,NaN,NaN,6.0
44,NaN,438,36,0.089612,4,NaN,NaN,NaN,5.0
43,NaN,624,28,0.058846,4,NaN,NaN,NaN,4.0
42,NaN,267,2,0.040000,4,NaN,NaN,NaN,3.0
41,NaN,609,4,0.024959,4,NaN,NaN,NaN,2.0
40,NaN,587,2,0.005468,4,NaN,NaN,NaN,1.0